pub mod cfg;
pub mod hs;
pub mod login;
pub mod play;

use bytes::Bytes;
use crate::error::{Err, R};
use crate::varint::read_var32_bytes;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State { Handshake, Status, Login, Config, Play }

pub enum C2S {
    Handshake(hs::Handshake),
    LoginStart(login::LoginStart),
    EncResponse(login::EncResponse),
    LoginAck(login::LoginAck),
    CfgPluginMsg(cfg::c2s::PluginMsg),
    CfgAckFinish(cfg::AckFinishCfg),
    CfgKeepAlive(cfg::CfgKeepAliveC2S),
    CfgKnownPacks(cfg::KnownPacksC2S),
    MovePos(play::c2s::MovePlayerPos),
    MoveRot(play::c2s::MovePlayerRot),
    MoveFull(play::c2s::MovePlayerFull),
    MoveGround(play::c2s::MovePlayerOnGround),
    Interact(play::c2s::Interact),
    UseItemOn(play::c2s::UseItemOn),
    UseItem(play::c2s::UseItem),
    Chat(play::c2s::Chat),
    Command(play::c2s::Command),
    KeepAlive(play::c2s::KeepAlive),
    Pong(play::c2s::Pong),
    ClientInfo(play::c2s::ClientInfo),
    ClickContainer(play::c2s::ClickContainer),
    CloseContainer(play::c2s::CloseContainer),
    CreativeInv(play::c2s::CreativeInv),
    DropItem(play::c2s::DropItem),
    SwingArm(play::c2s::SwingArm),
    PlayerCommand(play::c2s::PlayerCommand),
    PluginMsg(play::c2s::PluginMsg),
    ConfirmTp(play::c2s::ConfirmTp),
    Unknown(i32, Bytes),
}

pub enum S2C {
    LoginDisconnect(login::LoginDisconnect),
    EncRequest(login::EncRequest),
    LoginSuccess(login::LoginSuccess),
    SetCompress(login::SetCompress),
    CfgDisconnect(cfg::CfgDisconnect),
    CfgPluginMsg(cfg::CfgPluginMsg),
    FinishCfg(cfg::FinishCfg),
    CfgKeepAlive(cfg::CfgKeepAliveS2C),
    KnownPacks(cfg::KnownPacksS2C),
    FeatureFlags(cfg::FeatureFlags),
    Login(play::s2c::Login),
    Respawn(play::s2c::Respawn),
    PlayerPosition(play::s2c::PlayerPosition),
    PlayerAbilities(play::s2c::PlayerAbilities),
    SetHealth(play::s2c::SetHealth),
    SetExperience(play::s2c::SetExperience),
    GameEvent(play::s2c::GameEvent),
    Disconnect(play::s2c::Disconnect),
    ChunkData(play::s2c::ChunkData),
    BlockUpdate(play::s2c::BlockUpdate),
    SetCenterChunk(play::s2c::SetCenterChunk),
    UnloadChunk(play::s2c::UnloadChunk),
    SetTime(play::s2c::SetTime),
    SpawnEntity(play::s2c::SpawnEntity),
    RemoveEntities(play::s2c::RemoveEntities),
    MoveEntityPos(play::s2c::MoveEntityPos),
    MoveEntityRot(play::s2c::MoveEntityRot),
    SetEntityVelocity(play::s2c::SetEntityVelocity),
    ContainerContent(play::s2c::ContainerContent),
    ContainerSlot(play::s2c::ContainerSlot),
    OpenScreen(play::s2c::OpenScreen),
    SetCarryItem(play::s2c::SetCarryItem),
    SystemChat(play::s2c::SystemChat),
    PlayerChat(play::s2c::PlayerChat),
    DisguisedChat(play::s2c::DisguisedChat),
    KeepAlive(play::s2c::KeepAlive),
    Ping(play::s2c::Ping),
    PluginMsg(play::s2c::PluginMsg),
    TitleText(play::s2c::TitleText),
    SubtitleText(play::s2c::SubtitleText),
    ActionBar(play::s2c::ActionBar),
    ClearTitles(play::s2c::ClearTitles),
    TitleTimes(play::s2c::TitleTimes),
    TablistHeader(play::s2c::TablistHeader),
    Unknown(i32, Bytes),
}

pub fn decode_c2s(mut raw: Bytes, state: State) -> R<C2S> {
    let id = read_var32_bytes(&mut raw)?;
    Ok(match (state, id) {
        (State::Handshake, 0x00) => C2S::Handshake(hs::Handshake::decode(raw)?),
        (State::Login, 0x00) => C2S::LoginStart(login::LoginStart::decode(raw)?),
        (State::Login, 0x01) => C2S::EncResponse(login::EncResponse::decode(raw)?),
        (State::Login, 0x03) => C2S::LoginAck(login::LoginAck),
        (State::Config, 0x01) => C2S::CfgPluginMsg(cfg::c2s::PluginMsg::decode(raw)?),
        (State::Config, 0x02) => C2S::CfgAckFinish(cfg::AckFinishCfg),
        (State::Config, 0x03) => C2S::CfgKeepAlive(cfg::c2s::KeepAlive::decode(raw)?),
        (State::Config, 0x06) => C2S::CfgKnownPacks(cfg::c2s::KnownPacks::decode(raw)?),
        (State::Play, 0x00) => C2S::ConfirmTp(play::c2s::ConfirmTp::decode(raw)?),
        (State::Play, 0x06) => C2S::Chat(play::c2s::Chat::decode(raw)?),
        (State::Play, 0x04) => C2S::Command(play::c2s::Command::decode(raw)?),
        (State::Play, 0x08) => C2S::ClientInfo(play::c2s::ClientInfo::decode(raw)?),
        (State::Play, 0x0C) => C2S::ClickContainer(play::c2s::ClickContainer::decode(raw)?),
        (State::Play, 0x0D) => C2S::CloseContainer(play::c2s::CloseContainer::decode(raw)?),
        (State::Play, 0x12) => C2S::PluginMsg(play::c2s::PluginMsg::decode(raw)?),
        (State::Play, 0x13) => C2S::Interact(play::c2s::Interact::decode(raw)?),
        (State::Play, 0x18) => C2S::KeepAlive(play::c2s::KeepAlive::decode(raw)?),
        (State::Play, 0x1A) => C2S::MovePos(play::c2s::MovePlayerPos::decode(raw)?),
        (State::Play, 0x1B) => C2S::MoveRot(play::c2s::MovePlayerRot::decode(raw)?),
        (State::Play, 0x1C) => C2S::MoveFull(play::c2s::MovePlayerFull::decode(raw)?),
        (State::Play, 0x1D) => C2S::MoveGround(play::c2s::MovePlayerOnGround::decode(raw)?),
        (State::Play, 0x22) => C2S::DropItem(play::c2s::DropItem::decode(raw)?),
        (State::Play, 0x25) => C2S::PlayerCommand(play::c2s::PlayerCommand::decode(raw)?),
        (State::Play, 0x26) => C2S::Pong(play::c2s::Pong::decode(raw)?),
        (State::Play, 0x35) => C2S::SwingArm(play::c2s::SwingArm::decode(raw)?),
        (State::Play, 0x36) => C2S::UseItemOn(play::c2s::UseItemOn::decode(raw)?),
        (State::Play, 0x37) => C2S::UseItem(play::c2s::UseItem::decode(raw)?),
        (State::Play, 0x3B) => C2S::CreativeInv(play::c2s::CreativeInv::decode(raw)?),
        _ => C2S::Unknown(id, raw),
    })
}
