pub mod hs;
pub mod login;
pub mod play;

use bytes::Bytes;
use crate::error::{Err, R};

pub enum Pkt {
    RpInfo(login::RpInfo),
    RpResp(login::RpResp),
    RpStack(login::RpStack),
    RpDataInfo(login::RpDataInfo),
    RpChunk(login::RpChunk),
    StartGame(login::StartGame),
    PlayStatus(play::s2c::PlayStatusPkt),
    Disconnect(play::s2c::Disconnect),
    NetworkSettings(play::s2c::NetworkSettings),
    LevelChunk(play::s2c::LevelChunk),
    UpdateBlock(play::s2c::UpdateBlock),
    ChunkRadius(play::s2c::ChunkRadiusUpdated),
    AddPlayer(play::s2c::AddPlayer),
    RemoveEntity(play::s2c::RemoveEntity),
    MoveEntity(play::s2c::MoveEntity),
    SetHealth(play::s2c::SetHealth),
    InvContent(play::s2c::InvContent),
    InvSlot(play::s2c::InvSlot),
    ContainerOpen(play::s2c::ContainerOpen),
    SetTime(play::s2c::SetTime),
    SetDifficulty(play::s2c::SetDifficulty),
    LevelEvent(play::s2c::LevelEvent),
    SoundEvent(play::s2c::SoundEvent),
    Title(play::s2c::Title),
    Toast(play::s2c::Toast),
    GameMode(play::s2c::GameMode),
    Transfer(play::s2c::Transfer),
    SetSpawn(play::s2c::SetSpawn),
    MovePlayer(play::c2s::MovePlayer),
    Interact(play::c2s::Interact),
    BlockBreak(play::c2s::BlockBreak),
    BlockPlace(play::c2s::BlockPlace),
    InvTrans(play::c2s::InvTrans),
    ItemUse(play::c2s::ItemUse),
    ContainerClose(play::c2s::ContainerClose),
    Text(play::c2s::Text),
    Animate(play::c2s::Animate),
    Respawn(play::c2s::Respawn),
    Unknown(u8, Bytes),
}

pub fn decode(raw: Bytes) -> R<Pkt> {
    if raw.is_empty() { return Err(Err::Eof); }
    let id = raw[0];
    Ok(match id {
        0x02 => Pkt::PlayStatus(play::s2c::PlayStatusPkt::decode(raw)?),
        0x05 => Pkt::Disconnect(play::s2c::Disconnect::decode(raw)?),
        0x06 => Pkt::RpInfo(login::RpInfo::decode(raw)?),
        0x07 => Pkt::RpStack(login::RpStack::decode(raw)?),
        0x08 => Pkt::RpResp(login::RpResp::decode(raw)?),
        0x09 => Pkt::Text(play::c2s::Text::decode(raw)?),
        0x0B => Pkt::StartGame(login::StartGame::decode(raw)?),
        0x11 => Pkt::MoveEntity(play::s2c::MoveEntity::decode(raw)?),
        0x13 => Pkt::MovePlayer(play::c2s::MovePlayer::decode(raw)?),
        0x15 => Pkt::UpdateBlock(play::s2c::UpdateBlock::decode(raw)?),
        0x17 => Pkt::BlockBreak(play::c2s::BlockBreak::decode(raw)?),
        0x19 => Pkt::LevelEvent(play::s2c::LevelEvent::decode(raw)?),
        0x1C => Pkt::BlockPlace(play::c2s::BlockPlace::decode(raw)?),
        0x1E => Pkt::InvTrans(play::c2s::InvTrans::decode(raw)?),
        0x1F => Pkt::ItemUse(play::c2s::ItemUse::decode(raw)?),
        0x21 => Pkt::Interact(play::c2s::Interact::decode(raw)?),
        0x26 => Pkt::SetHealth(play::s2c::SetHealth::decode(raw)?),
        0x2C => Pkt::Animate(play::c2s::Animate::decode(raw)?),
        0x2E => Pkt::ContainerOpen(play::s2c::ContainerOpen::decode(raw)?),
        0x2F => Pkt::ContainerClose(play::c2s::ContainerClose::decode(raw)?),
        0x31 => Pkt::InvContent(play::s2c::InvContent::decode(raw)?),
        0x32 => Pkt::InvSlot(play::s2c::InvSlot::decode(raw)?),
        0x35 => Pkt::Respawn(play::c2s::Respawn::decode(raw)?),
        0x3A => Pkt::LevelChunk(play::s2c::LevelChunk::decode(raw)?),
        0x3C => Pkt::SetDifficulty(play::s2c::SetDifficulty::decode(raw)?),
        0x3F => Pkt::GameMode(play::s2c::GameMode::decode(raw)?),
        0x43 => Pkt::SetSpawn(play::s2c::SetSpawn::decode(raw)?),
        0x45 => Pkt::ChunkRadius(play::s2c::ChunkRadiusUpdated::decode(raw)?),
        0x52 => Pkt::RpDataInfo(login::RpDataInfo::decode(raw)?),
        0x53 => Pkt::RpChunk(login::RpChunk::decode(raw)?),
        0x55 => Pkt::Transfer(play::s2c::Transfer::decode(raw)?),
        0x58 => Pkt::Title(play::s2c::Title::decode(raw)?),
        0x7B => Pkt::SoundEvent(play::s2c::SoundEvent::decode(raw)?),
        0x8F => Pkt::NetworkSettings(play::s2c::NetworkSettings::decode(raw)?),
        0x0C => Pkt::AddPlayer(play::s2c::AddPlayer::decode(raw)?),
        0x0E => Pkt::RemoveEntity(play::s2c::RemoveEntity::decode(raw)?),
        0xBB => Pkt::Toast(play::s2c::Toast::decode(raw)?),
        x    => Pkt::Unknown(x, raw),
    })
}
