use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[repr(u32)]
pub enum Kind {
    Player        = 0,
    Zombie        = 1,
    Skeleton      = 2,
    Creeper       = 3,
    Spider        = 4,
    Enderman      = 5,
    Witch         = 6,
    Blaze         = 7,
    Ghast         = 8,
    Slime         = 9,
    MagmaCube     = 10,
    Pig           = 11,
    Cow           = 12,
    Sheep         = 13,
    Chicken       = 14,
    Horse         = 15,
    Wolf          = 16,
    Cat           = 17,
    Fox           = 18,
    Bee           = 19,
    Villager      = 20,
    IronGolem     = 21,
    SnowGolem     = 22,
    Bat           = 23,
    Squid         = 24,
    Dolphin       = 25,
    ItemEntity    = 100,
    ExperienceOrb = 101,
    PrimedTnt     = 102,
    FallingBlock  = 103,
    Boat          = 104,
    Minecart      = 105,
    Arrow         = 106,
    Fireball      = 107,
    Snowball      = 108,
    Egg           = 109,
    EnderPearl    = 110,
    Unknown       = 0xFFFF,
}

impl Kind {
    pub fn from_java_id(id: i32) -> Self {
        match id {
            0  => Self::Player,
            37 => Self::Zombie,
            60 => Self::Skeleton,
            19 => Self::Creeper,
            77 => Self::Spider,
            27 => Self::Enderman,
            99 => Self::Witch,
            8  => Self::Blaze,
            36 => Self::Ghast,
            62 => Self::Slime,
            55 => Self::MagmaCube,
            63 => Self::Pig,
            15 => Self::Cow,
            73 => Self::Sheep,
            18 => Self::Chicken,
            47 => Self::Horse,
            101 => Self::Wolf,
            16 => Self::Cat,
            30 => Self::Fox,
            6  => Self::Bee,
            88 => Self::Villager,
            41 => Self::IronGolem,
            76 => Self::SnowGolem,
            7  => Self::Bat,
            79 => Self::Squid,
            26 => Self::Dolphin,
            _  => Self::Unknown,
        }
    }

    pub fn from_bedrock_id(id: i32) -> Self {
        match id {
            1   => Self::Player,
            32  => Self::Zombie,
            34  => Self::Skeleton,
            33  => Self::Creeper,
            35  => Self::Spider,
            38  => Self::Enderman,
            45  => Self::Witch,
            43  => Self::Blaze,
            41  => Self::Ghast,
            37  => Self::Slime,
            42  => Self::MagmaCube,
            12  => Self::Pig,
            11  => Self::Cow,
            13  => Self::Sheep,
            10  => Self::Chicken,
            23  => Self::Horse,
            14  => Self::Wolf,
            75  => Self::Cat,
            121 => Self::Fox,
            122 => Self::Bee,
            15  => Self::Villager,
            20  => Self::IronGolem,
            21  => Self::SnowGolem,
            19  => Self::Bat,
            17  => Self::Squid,
            31  => Self::Item,
            64  => Self::ExperienceOrb,
            65  => Self::PrimedTnt,
            66  => Self::FallingBlock,
            90  => Self::Boat,
            84  => Self::Minecart,
            80  => Self::Arrow,
            85  => Self::Fireball,
            81  => Self::Snowball,
            82  => Self::Egg,
            87  => Self::EnderPearl,
            _   => Self::Unknown,
        }
    }
}

impl Kind {
    const fn Item() -> Self { Self::ItemEntity }
}
